// Generated by CoffeeScript 2.0.0-beta8
void function () {
  var debounce, domReady;
  domReady = Q.promise(function (resolve) {
    var handler;
    handler = resolve.bind(null, document);
    document.addEventListener('DOMContentLoaded', handler, false);
    return window.addEventListener('load', handler, false);
  });
  debounce = function (ms, func) {
    var callback, savedArgs, savedContext, timeout;
    timeout = null;
    savedContext = null;
    savedArgs = null;
    callback = function () {
      return func.apply(savedContext, savedArgs);
    };
    return function (args) {
      args = 1 <= arguments.length ? [].slice.call(arguments, 0) : [];
      if (null != timeout)
        clearTimeout(timeout);
      savedContext = this;
      savedArgs = args;
      timeout = setTimeout(callback, ms);
    };
  };
  domReady.then(function () {
    return new vidius.Assets().loadText('shaders/sprite-renderer.glsl').loadImage('assets/arrow.png').loadImage('assets/cursor.png').loadImage('assets/electric.png').loadImage('assets/font.png').loadImage('assets/overlay.png').loadImage('assets/vidius.png').loadSample('assets/bang.wav').loadSample('assets/beep.wav').loadSample('assets/donk.wav').wait();
  }).then(function (assets) {
    var arrow, cursor, debugView, displayList, font, logo1, logo2, packer;
    DisplayList.prototype.shaderSource = assets.sprite_renderer_glsl;
    displayList = new gfx.DisplayList(document.getElementById('display'), 256, 192, 128, assets.overlay_png);
    font = new gfx.BitmapFont(assets.font_png);
    packer = new gfx.TexturePacker(128);
    logo1 = displayList.createSprite(assets.vidius_png).move(80, -32);
    logo2 = displayList.createSprite(assets.electric_png).move(80, 104);
    arrow = displayList.createSprite(assets.arrow_png).move(80, 176);
    cursor = displayList.createSprite(assets.cursor_png).move(0, 0);
    debugView = document.querySelector('#debug');
    debugView.appendChild(displayList.texturePacker.texture);
    debugView.appendChild(font.image);
    document.addEventListener('keydown', function (event) {
      if (event.keyCode === 192)
        if (debugView.style.display === 'block') {
          return debugView.style.display = 'none';
        } else {
          return debugView.style.display = 'block';
        }
    }, false);
    new TWEEN.Tween(logo1.pos).to({ y: 80 }, 2e3).onStart(function () {
      return displayList.add(logo1);
    }).onComplete(function () {
      var i, link;
      displayList.add(logo2);
      setTimeout(function () {
        return new TWEEN.Tween(arrow.pos).to({ y: arrow.pos.y - 16 }, 500).easing(TWEEN.Easing.Quadratic.InOut).repeat(5).yoyo(true).onStart(function () {
          return displayList.add(arrow);
        }).onComplete(function () {
          return displayList.remove(arrow);
        }).start();
      }, 500);
      assets.bang_wav.play();
      document.querySelector('#navigation').classList.add('highlight');
      return function (accum$) {
        for (var cache$ = document.querySelectorAll('#navigation a'), i$ = 0, length$ = cache$.length; i$ < length$; ++i$) {
          link = cache$[i$];
          i = i$;
          accum$.push(function (link) {
            var image, sprite, x, y;
            image = font.textToImage(link.textContent);
            x = (256 - image.width) / 2;
            y = 120 + i * font.height;
            sprite = displayList.createSprite(image).move(x, y);
            displayList.add(sprite);
            link.addEventListener('mouseenter', function () {
              cursor.move(x - 16, y);
              displayList.add(cursor);
              assets.donk_wav.pause();
              assets.beep_wav.currentTime = 0;
              return assets.beep_wav.play();
            }, false);
            return link.addEventListener('mouseleave', function () {
              displayList.remove(cursor);
              assets.beep_wav.pause();
              assets.donk_wav.currentTime = 0;
              return assets.donk_wav.play();
            }, false);
          }(link));
        }
        return accum$;
      }.call(this, []);
    }).start();
    return displayList.start();
  }).done();
}.call(this);

//# sourceMappingURL=bootlogo.map
